### ISSUE TITLE
Swagger output in Symfony 3.0 and lower

### ISSUE THREAD

**Issue by lubomir-haralampiev** [TimeIncOSS/swagger-bundle#10]
In Symfony versions 3.0 and lower the swagger output gets json encoded twice when processed by the SwaggerController. The reason is that a JsonResponse accepts already encoded data starting from version 3.1.

I fixed it and made a pull request for that - #9 

I like your approach and it would be great if we can keep the bundle compatible with the versions with long term support.

Thanks for sharing

**Comment by andythorne** [comment]
PR #9 Merged, Thank you!
