### ISSUE TITLE
  You must call one of in() or append() methods before iterating over a Finder.  error

### ISSUE THREAD

**Issue by Mohammadtrabelsi** [TimeIncOSS/swagger-bundle#16]
I work with **symfony project** and i want to generate documentation for my **REST Web Service**  based on **swagger 2**,so i installed **swagger-bundle** and i configurid it. but when i tri to generate the json api documenation with this command

> app/console -e=dev swagger:dump

i got this error:

> You must call one of in() or append() methods before iterating over a Finder.
this is my config file

```
swagger:
    version: '2.0'
    info:
        title: 'My API'
        version: '1.0.0'
        description: 'My API Description'
    host: '127.0.0.1'
    base_path: '/v2'
    schemes:
        - http
    produces:
        - application/json
    consumes:
        - application/json
    annotations:
        bundles:
            - BOBundleBundle
```
this is the exception trace:

> 
>  () at /projet/myproject/vendor/symfony/symfony/src/Symfony/Component/Finder/Finder.php:677
>  Symfony\Component\Finder\Finder->getIterator() at /projet/myproject/vendor/timeinc/swagger-bundle/src/Swagger.php:62
>  TimeInc\SwaggerBundle\Swagger->build() at /projet/myproject/vendor/timeinc/swagger-bundle/src/Swagger.php:82
>  TimeInc\SwaggerBundle\Swagger->json() at /projet/myproject/vendor/timeinc/swagger-bundle/src/Command/DumpCommand.php:44
>  TimeInc\SwaggerBundle\Command\DumpCommand->execute() at /projet/myproject/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:259
>  Symfony\Component\Console\Command\Command->run() at /projet/myproject/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:866
>  Symfony\Component\Console\Application->doRunCommand() at /projet/myproject/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:193
>  Symfony\Component\Console\Application->doRun() at /projet/myproject/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:92
>  Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /projet/myproject/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:124
>  Symfony\Component\Console\Application->run() at /projet/myproject/app/console:27

any help please.

**Comment by andythorne** [comment]
Hi @Mohammadtrabelsi, I think there's 1 of 2 things that could be causing this issue:

- When the symfony configs are parsed, the bundle will loop the regsitered bundle names and check if the are enable in the config at `swagger.annotations.bundles`. I see you have enabled your bundle `BOBundleBundle`, which is good. The name must match exactly, so please make sure it matches.
- The bundle will look in the directories [listed here](https://github.com/TimeIncOSS/swagger-bundle/blob/master/src/DependencyInjection/SwaggerExtension.php#L55-L60). Please ensure at least one of these directories exist in your bundle.

Let me know if it helps :)

**Comment by Mohammadtrabelsi** [comment]
@andythorne
Very helpful Bro ! thanks a lot!
