### ISSUE TITLE
Annotation can not be loaded

### ISSUE THREAD

**Issue by RauchF** [TimeIncOSS/swagger-bundle#22]
Using the `@Route` annotation as documented does not work as expected:

## Prerequisites
Given a bundle with a route annotation like this:
```php
use TimeInc\SwaggerBundle\Swagger\Annotation\Route;

class BundleController extends Controller
{
    /**
     * @Route(route="bundle_list", returns="collection", method="GET")
     */
    public function listAction()
    {
        // code
    }
```

## Expected behaviour
I would expect the annotation to get parsed, allowing me to use it.

## Actual behaviour
The following error occurs:
```
PHP Fatal error:  Uncaught Doctrine\Common\Annotations\AnnotationException: [Semantical Error] The annotation "@TimeInc\SwaggerBundle\Swagger\Annotation\Route" in method Kerbdoch\Lovi\TallyBundle\Controller\BundleController::listAction() does not exist, or could not be auto-loaded. in {my-project-dir}\vendor\doctrine\annotations\lib\Doctrine\Common\Annotations\AnnotationException.php:54
Stack trace:
#0 {my-project-dir}\vendor\doctrine\annotations\lib\Doctrine\Common\Annotations\DocParser.php(734): Doctrine\Common\Annotations\AnnotationException::semanticalError('The annotation ...')
#1 {my-project-dir}\vendor\doctrine\annotations\lib\Doctrine\Common\Annotations\DocParser.php(663): Doctrine\Common\Annotations\DocParser->Annotation()
#2 {my-project-dir}\vendor\doctrine\annotations\lib\Doctrine\Common\Annotations\DocParser.php(354): Doctrine\Common\Annotations\DocParser->Annotations()
....
```

I have tracked it down to the annotation loader that gets registered in `\TimeInc\SwaggerBundle\DependencyInjection\SwaggerExtension::load()`. The `$class` parameter passed to the loader function is `(string) "TimeInc\SwaggerBundle\Swagger\Annotation\Route"` (according to XDebug), so the check `file_exists($dir.'/Swagger/Annotation/'.$class.'.php')` returns `false`.

## Environment
I am using:
 - Windows 10
 - PHP 7.1.5
 - Symfony 3.3.*
 - SwaggerBundle 0.2.1

---
Thank you for your help

**Comment by andythorne** [comment]
Good spot. I'm not sure that the annotation register function every worked properly. I can only assume that on unix systems, Doctrine can get the correct file based on the namespace. I'll make a PR to fix your issue soon.
