### ISSUE TITLE
[bundle_dir]/Swagger is ignored

### ISSUE THREAD

**Issue by hipio** [TimeIncOSS/swagger-bundle#8]
I've noticed that my PHP file with swagger-php annotations (Entity definitions) is ignored when put in the `Swagger` directory. It works fine if I add it to the `Entity` folder, but the `Swagger` one is ignored. 

See this screenshot to see how my bundle structure looks like
![screen shot 2016-09-28 at 10 40 04](https://cloud.githubusercontent.com/assets/3717518/18906539/31caf8d0-8568-11e6-8647-4702f7bed7f4.png)

**Comment by hipio** [comment]
Nevermind, the namespace in my Swagger file was incorrect (it was `namespace Bla\V1\Resources`). Still odd that it worked when put in the Entities folder.

**Comment by andythorne** [comment]
That is odd as the same bit of code reads both directories, so there should be not difference. I'll keep an eye open for it.

**Comment by hipio** [comment]
@andythorne Was this odd behaviour resolved or did you never encounter it? Could be a bug on my system I suppose.

**Comment by andythorne** [comment]
Couldn't replicate I'm afraid - we use the `Swagger` folder and it seems to be working for us!

![image](https://cloud.githubusercontent.com/assets/1301181/20532859/6d2fdc1a-b0d3-11e6-9dee-25e733b2f29d.png)
